name: Collect APT Threat Feeds

on:
  schedule:
    # Run every 1 hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      update_maltrail:
        description: 'Update Maltrail repository'
        required: false
        default: true
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'apttrail_threat_feed_collector.py'
      - '.github/workflows/collect-apt-feeds.yml'

jobs:
  collect-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone/Update Maltrail repository
      run: |
        mkdir -p data
        if [ -d "data/maltrail" ]; then
          cd data/maltrail
          git pull origin master
          cd ../..
        else
          git clone https://github.com/stamparm/maltrail.git data/maltrail
        fi

    - name: Collect APT indicators
      run: |
        python apttrail_threat_feed_collector.py --output-dir feeds --collect-timestamps --suricata-dataset

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check if there are changes in feeds only
        git add feeds/

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Generate commit message with only changed groups
          python3 .github/scripts/generate_collection_report.py > collection_report.md

          if [ -s collection_report.md ]; then
            git commit -F collection_report.md
            git push
          else
            echo "No changes detected by report generator"
          fi
        fi

    - name: Create release (weekly)
      if: github.event_name == 'schedule' && contains('0 0 * * 0', github.event.schedule)
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: APT Threat Feeds Release ${{ github.run_number }}
        body_path: collection_report.md
        files: |
          feeds/apttrail_threat_feed.json
          feeds/apttrail_threat_feed.csv
          feeds/apttrail_threat_feed_metadata.csv
          feeds/apttrail_threat_feed.rules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}